import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
shell.program = "/bin/zsh"
[ env ]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"

[window.dimensions]
columns = 164  # Set the default number of columns
lines = 40     # Set the default number of lines



[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 13

