# Close Kitty when the last window is closed
confirm_os_window_close 0

# Set font
font_family Hack Nerd Font

# Set background opacity
background_opacity 0.7

# Set theme (Kitty doesn't support Monokai Pro Octagon by default, but you can install it manually)
include monokai_pro_octagon.conf

hide_window_decorations yes

# Hide macOS title bar
macos_titlebar_color none

# Allow clipboard writes
clipboard_control write-clipboard write-primary

# Set default shell to Zsh
shell zsh
foreground            #f8f8f2
background            #2e2a31
selection_foreground  #f8f8f2
selection_background  #403e41
url_color             #f8f8f2

cursor                #fc9867
cursor_text_color     background
active_border_color   #ab9df2
inactive_border_color #403e41

# Normal colors
color0  #2e2a31
color1  #ff6188
color2  #a9dc76
color3  #ffd866
color4  #fc9867
color5  #ab9df2
color6  #78dce8
color7  #f8f8f2

# Bright colors
color8  #727072
color9  #ff6188
color10 #a9dc76
color11 #ffd866
color12 #fc9867
color13 #ab9df2
color14 #78dce8
color15 #ffffff
