music_directory     "~/.music"
playlist_directory  "~/.music/mpd/playlists"
db_file             "~/.music/mpd/database"
log_file            "~/.music/mpd/log"
pid_file            "~/.music/mpd/pid"
state_file          "~/.music/mpd/state"
sticker_file        "~/.music/mpd/sticker.sql"

bind_to_address     "127.0.0.1"
port                "6600"
