[Interface]
PrivateKey = 6BP5PZxRcSUi5lAp+e74Enr2wt2VnWQyKogCoLnA03M=
Address = 10.200.200.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = kSLneflTRimBjH0vfywolGdTbGYAvcaxnNXAlshSXnQ=
Endpoint = 10.20.151.99:51820
AllowedIPs = 10.200.200.1/32
PersistentKeepalive = 25
